name: rand-tool # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python CLI tool for generating random numbers
description: |
  This is a test snap for a Python application that generates random numbers.
  Provides a few arguments to customize the output, including allowing users
  to seed the random number generator.

grade: devel
confinement: strict

parts:
  main:
    plugin: python
    source: .
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      chmod +x $SNAPCRAFT_PART_BUILD/bin/main
      cp $SNAPCRAFT_PART_BUILD/bin/main $SNAPCRAFT_PART_INSTALL/bin/main

apps:
  rand-tool:
    command: bin/main
